#! /bin/sh

polybar &
picom &
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &
#nitrogen --restore

#pipewire &
#wireplumber &
#pipewire-pulse &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color '#000000'
bspc config active_border_color '#999999'
bspc config focused_border_color '#ffffff'
bspc config presel_feedback_color '#00ff88'

bspc config border_width 4
