;;; scrollable-quick-peek-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from scrollable-quick-peek.el

(autoload 'scrollable-quick-peek-scroll-up "scrollable-quick-peek" "\
Scroll up in the currently displayed overlay." t)
(autoload 'scrollable-quick-peek-scroll-down "scrollable-quick-peek" "\
Scroll down in the currently displayed overlay." t)
(autoload 'scrollable-quick-peek-show "scrollable-quick-peek" "\
Show STR in an inline scrollable window at POS.
MIN-H (default: 4) and MAX-H (default: 16) are passed directly to
`quick-peek'. `quick-peek' also accepts a `'none' option for MIN-H
and MAX-H but these will not get passed given these don't make
sense for `scrollale-quick-peek'.

(fn STR &optional POS MIN-H MAX-H)" t)
(register-definition-prefixes "scrollable-quick-peek" '("scrollable-quick-peek"))

;;; End of scraped data

(provide 'scrollable-quick-peek-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; scrollable-quick-peek-autoloads.el ends here
